spring.application.name=campshare
spring.config.import=optional:file:./application-local.properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.locations=classpath:db/migration
server.port=8081
