CREATE TABLE gears (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    daily_price INTEGER NOT NULL CHECK (daily_price >= 0),
    stock_count INTEGER NOT NULL CHECK (stock_count >= 0),
    image_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO gears (name, category, description, daily_price, stock_count, image_url) VALUES
('ファミリードームテント', 'テント', '4人まで快適に過ごせる定番ドームテント。', 4500, 3, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80'),
('ヘキサタープ', 'タープ', '日差しや小雨を防ぐ、広々としたリビングスペース。', 2800, 4, 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&w=900&q=80'),
('LEDランタン', '照明', '暖色の光でサイトをやさしく照らすLEDランタン。', 800, 8, 'https://images.unsplash.com/photo-1517825738774-7de9363ef735?auto=format&fit=crop&w=900&q=80'),
('マミー型寝袋', '寝袋', '春から秋まで使える、軽量で暖かな寝袋。', 1500, 6, 'https://images.unsplash.com/photo-1501706362039-c6e13d0c7f3a?auto=format&fit=crop&w=900&q=80'),
('折りたたみテーブル', 'ファニチャー', '食事や調理に便利なコンパクトテーブル。', 1200, 5, 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=900&q=80'),
('リラックスチェア', 'ファニチャー', '焚き火時間をゆったり楽しめるローチェア。', 900, 10, 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80');
